FROM datadrone/deeplearn_pytorch:cuda10.0_opencv4.0.0

LABEL maintainer="Brian Law <bpl.law@gmail.com>"

USER root

RUN apt install -y curl && \
    apt-get -y install openjdk-8-jdk

RUN conda install -y tensorflow-gpu

USER $NB_USER
WORKDIR $HOME