FROM datadrone/deeplearn_opencv:cuda-10.1_opencv-4.1.1-jdk

LABEL maintainer="Brian Law <bpl.law@gmail.com>"

USER root

RUN apt install -y curl 

RUN conda install -y tensorflow-gpu #redo

USER $NB_USER
WORKDIR $HOME
