FROM datadrone/deeplearn_opencv:cuda-10.1_opencv-4.1.1

LABEL maintainer="Brian Law <bpl.law@gmail.com>"

# update to compile for cuda
RUN conda install -y numpy scipy matplotlib pandas scikit-learn

ENV CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"
RUN conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing && \
    conda install -c pytorch magma-cuda101

WORKDIR /opt

ENV TORCH_CUDA_ARCH_LIST=7.5

RUN git clone --recursive https://github.com/pytorch/pytorch && \
    cd pytorch && \
    git checkout tags/v1.4.0 && \
    git submodule sync && \
    git submodule update --init --recursive && \
    python setup.py install

WORKDIR /opt

#RUN conda install -c pytorch captum
RUN conda install -c conda-forge yarn && \
    git clone https://github.com/pytorch/captum.git && \
    cd captum && \
    git checkout tags/v0.1.0 && \
    pip install -e .[insights]

WORKDIR /opt

# issue with compiling with torch
# need to debug compile with 0.5.0 
ENV FORCE_CUDA=1
RUN git clone https://github.com/pytorch/vision.git && \
    cd vision && \
    git checkout tags/v0.5.0 && \
    python setup.py install

RUN conda install -c pytorch -c fastai fastai

# Dali plugin
RUN pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali

# need to wait till pytorch is compiled with cuda 10.1
WORKDIR /opt
RUN git clone https://github.com/NVIDIA/apex && \
    cd apex && \
    pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

WORKDIR $HOME

USER $NB_USER
