FROM datadrone/deeplearn_opencv:cuda-10.1_opencv-4.1.1

LABEL maintainer="Brian Law <bpl.law@gmail.com>"

RUN conda install -y numpy scipy matplotlib pandas scikit-learn
RUN conda install -y pytorch torchvision cudatoolkit=10.0 -c pytorch
# currently broken
#RUN conda install -y -c fastai fastai

# Dali plugin
RUN pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali

WORKDIR /opt
RUN git clone https://github.com/NVIDIA/apex && \
    cd apex && \
    pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./


WORKDIR $HOME

USER $NB_USER