FROM datadrone/deeplearn_minimal:cuda-9.2

LABEL maintainer="Brian Law <bpl.law@gmail.com>"

RUN conda install -y numpy scipy matplotlib pandas scikit-learn
RUN conda install -y -c conda-forge opencv
RUN conda install -y -c pytorch torchvision


